// Choice-based encounter templates — each has 3 approach options
// Thresholds are BASE values; +1 per overall character level is added at generation time

export const ENCOUNTER_TEMPLATES = [
  // ═══════════ Combat Encounters ═══════════
  {
    id: 'goblin_ambush',
    title: 'Goblin Ambush',
    sceneType: 'combat',
    intro: 'A pack of {monster} leaps from the shadows of {location}! Their rusted blades glint in the torchlight as they surround you.',
    choices: [
      { label: 'Charge and fight', stat: 'STR', baseThreshold: 2, successText: 'Your blade cleaves true — the {monster} scatter before your might! Among the wreckage you discover {loot}.', failureText: 'The {monster} overwhelm you with sheer numbers. You barely escape {location} bruised but wiser.' },
      { label: 'Set a clever trap', stat: 'INT', baseThreshold: 3, successText: 'Your trap springs perfectly! The {monster} tumble into a pit you rigged. {loot} falls from their pockets.', failureText: 'Your trap misfires spectacularly. The {monster} step right over it and chase you out of {location}.' },
      { label: 'Bluff and intimidate', stat: 'CRE', baseThreshold: 2, successText: 'You roar with such ferocity that the {monster} believe you\'re a demon lord! They drop {loot} and flee.', failureText: 'The {monster} see right through your bluff. "Nice try, human." They steal your lunch.' },
    ],
    monsters: ['Goblin Warchief', 'Feral Kobolds', 'Bandit Raiders', 'Gnoll Scouts'],
    locations: ['the Whispering Caverns', 'a crumbling watchtower', 'the Duskwood trail', 'an ancient tomb entrance'],
    loot: ['Enchanted Shortsword', 'Iron Shield of Valor', 'Gauntlets of Power', 'Warrior\'s Amulet'],
    baseXP: 2,
  },
  {
    id: 'bridge_guardian',
    title: 'Bridge Guardian',
    sceneType: 'combat',
    intro: 'A massive {monster} blocks the narrow bridge over {location}. Its stone fists crack the air as it roars: "NONE SHALL PASS!"',
    choices: [
      { label: 'Match it blow for blow', stat: 'STR', baseThreshold: 3, successText: 'You match the {monster} blow for blow until it crumbles! In the rubble, you find {loot}.', failureText: 'The {monster} hurls you back with a thunderous blow. You\'ll need to find another way across {location}.' },
      { label: 'Find its weakness', stat: 'INT', baseThreshold: 2, successText: 'You spot a cracked rune on its chest — one precise strike and the {monster} shatters! {loot} gleams inside.', failureText: 'You study it too long. The {monster} loses patience and punts you across {location}.' },
      { label: 'Outlast its energy', stat: 'VIT', baseThreshold: 3, successText: 'You dodge and weave for what feels like hours. The {monster} exhausts itself and collapses. {loot} is yours!', failureText: 'Your stamina gives out first. The {monster} stands guard as you collapse, panting, at the edge of {location}.' },
    ],
    monsters: ['Stone Golem', 'Troll Warlord', 'Iron Construct', 'Ettin Gatekeeper'],
    locations: ['the Abyssal Gorge', 'the River of Echoes', 'Dragonfire Canyon', 'the Moonlit Chasm'],
    loot: ['Belt of Giant Strength', 'Helm of Fortitude', 'Boots of the Mountain', 'Ring of the Titan'],
    baseXP: 2,
  },
  {
    id: 'collapsed_tunnel',
    title: 'Collapsed Tunnel',
    sceneType: 'combat',
    intro: 'The ceiling of {location} gives way! Through the dust and rubble, you hear cries — {monster} are trapped beneath fallen stone.',
    choices: [
      { label: 'Lift the boulders', stat: 'STR', baseThreshold: 2, successText: 'Muscles burning, you heave the boulders aside. The {monster} are freed! In gratitude, they offer you {loot}.', failureText: 'The stones are too heavy. Other rescuers eventually arrive, but you couldn\'t do it alone.' },
      { label: 'Engineer a lever system', stat: 'INT', baseThreshold: 3, successText: 'Using a beam and fulcrum, you lever the rubble aside with physics! The {monster} gift you {loot} in awe.', failureText: 'Your makeshift lever snaps. Back to square one. The {monster} look disappointed.' },
      { label: 'Rally others to help', stat: 'CRE', baseThreshold: 2, successText: 'Your inspiring speech rallies nearby travelers. Together you clear the rubble! The {monster} present you with {loot}.', failureText: 'Nobody listens to your speech. They walk past. Awkward.' },
    ],
    monsters: ['trapped villagers', 'dwarven miners', 'young adventurers', 'elvish scholars'],
    locations: ['the Deepstone Mines', 'the Undercity passages', 'a forgotten catacomb', 'the Crystal Tunnels'],
    loot: ['Potion of Bull\'s Strength', 'Ancient Warhammer', 'Bracers of Might', 'Stone of Endurance'],
    baseXP: 2,
  },
  {
    id: 'arm_wrestling_ogre',
    title: 'The Ogre\'s Challenge',
    sceneType: 'combat',
    intro: 'At a crossroads tavern in {location}, a boisterous {monster} slams a meaty fist on the table. "You! Arm wrestle me! Winner takes all!"',
    choices: [
      { label: 'Accept the challenge', stat: 'STR', baseThreshold: 3, successText: 'The table cracks as you slam the {monster}\'s arm down! The crowd erupts! The ogre tosses you {loot}.', failureText: 'The {monster} pins your arm in seconds and laughs. "Better luck next time, tiny warrior!"' },
      { label: 'Distract and cheat', stat: 'CRE', baseThreshold: 2, successText: '"Look, a dragon!" The {monster} turns — you slam their arm down. The crowd doesn\'t care HOW you won. {loot} is yours!', failureText: 'The {monster} doesn\'t fall for it. "You think I\'m stupid?" Well, this is embarrassing.' },
      { label: 'Bet on endurance instead', stat: 'VIT', baseThreshold: 2, successText: 'You hold the stalemate for 20 minutes. The {monster}\'s arm trembles first. Victory through sheer endurance! {loot} earned.', failureText: 'Your arm gives out at minute 3. The {monster} orders you a consolation drink.' },
    ],
    monsters: ['Grog the Undefeated', 'an Ogre Champion', 'a Mountain Troll', 'the Tavern Titan'],
    locations: ['the Rusty Flagon', 'the Dragon\'s Belly Inn', 'Hearthstone Tavern', 'the Wanderer\'s Rest'],
    loot: ['Potion of Might', 'Golden Armband', 'Champion\'s Trophy', 'Enchanted Grip Wraps'],
    baseXP: 2,
  },

  // ═══════════ Puzzle Encounters ═══════════
  {
    id: 'arcane_lock',
    title: 'The Arcane Lock',
    sceneType: 'puzzle',
    intro: 'Before you stands a sealed vault door in {location}. Shimmering runes pulse across its surface — {monster} left this puzzle centuries ago.',
    choices: [
      { label: 'Decipher the runes', stat: 'INT', baseThreshold: 2, successText: 'The runes align under your touch! The vault opens, revealing {loot} bathed in ancient light.', failureText: 'The runes flash angrily and reset. The puzzle remains unsolved... for now.' },
      { label: 'Force the door open', stat: 'STR', baseThreshold: 3, successText: 'With a mighty heave, you rip the vault door from its hinges! Who needs puzzles? {loot} awaits inside.', failureText: 'You push until your muscles scream. The door doesn\'t budge. Not even a little.' },
      { label: 'Meditate for insight', stat: 'WIL', baseThreshold: 2, successText: 'In deep focus, the answer flows to you like water. The vault whispers open. Inside: {loot}.', failureText: 'You meditate for an hour and fall asleep against the door. You dream of the answer but forget it upon waking.' },
    ],
    monsters: ['an Archmage', 'the Elven Artificers', 'a forgotten Lich', 'the Mage Council'],
    locations: ['the Obsidian Vault', 'the Library of Eternity', 'a hidden wizard\'s tower', 'the Runic Sanctum'],
    loot: ['Tome of Infinite Knowledge', 'Crystal Orb of Insight', 'Scroll of Ancient Wisdom', 'Circlet of the Mind'],
    baseXP: 2,
  },
  {
    id: 'sphinx_riddle',
    title: 'The Sphinx\'s Riddle',
    sceneType: 'puzzle',
    intro: '{monster} blocks the mountain pass of {location}, its ancient eyes gleaming. "Answer my riddle, mortal, or turn back forever."',
    choices: [
      { label: 'Solve the riddle', stat: 'INT', baseThreshold: 3, successText: 'Your answer echoes through the mountains. {monster} nods and steps aside. Behind it lies {loot}.', failureText: '{monster} shakes its massive head. "Incorrect. The pass is closed to you today."' },
      { label: 'Charm the sphinx', stat: 'CRE', baseThreshold: 2, successText: 'You tell such a captivating story that {monster} forgets about the riddle entirely! It waves you through with {loot}.', failureText: '"Flattery won\'t work on a being older than your civilization," says {monster} dryly.' },
      { label: 'Stare it down', stat: 'WIL', baseThreshold: 3, successText: 'Your unwavering gaze impresses {monster}. "You have the will of the ancients." It steps aside, revealing {loot}.', failureText: '{monster}\'s psychic presence is overwhelming. You avert your eyes. Maybe next time.' },
    ],
    monsters: ['the Great Sphinx', 'an Elder Dragon', 'the Oracle of Storms', 'a Celestial Guardian'],
    locations: ['the Windswept Pass', 'the Gates of Wisdom', 'the Mountain of Trials', 'the Crossroads of Fate'],
    loot: ['Eye of Truth', 'Pendant of the Scholar', 'Ancient Star Map', 'Quill of Prophecy'],
    baseXP: 2,
  },
  {
    id: 'unstable_portal',
    title: 'The Unstable Portal',
    sceneType: 'puzzle',
    intro: 'A malfunctioning portal crackles in {location}, threatening to tear reality apart! {monster} tried to contain it but failed.',
    choices: [
      { label: 'Recalibrate the magic', stat: 'INT', baseThreshold: 2, successText: 'Your calculations are precise — the portal stabilizes! {monster} thanks you. Through the portal, you retrieve {loot}.', failureText: 'You accidentally make it worse. The portal hiccups and teleports everyone\'s shoes to another dimension.' },
      { label: 'Absorb the energy', stat: 'WIL', baseThreshold: 3, successText: 'You channel the chaotic energy through sheer willpower! The portal calms. {loot} materializes from the stabilized rift.', failureText: 'The energy overwhelms your focus. You get zapped across the room. Hair standing on end.' },
      { label: 'Physically contain it', stat: 'VIT', baseThreshold: 2, successText: 'You hold the portal frame steady with raw endurance while it burns out. {loot} drops from the fading rift!', failureText: 'The energy burns your hands. You let go. At least you tried, but {location} is now slightly on fire.' },
    ],
    monsters: ['the Arcane Academy', 'a desperate Warlock', 'the Planar Watchers', 'a panicked Artificer'],
    locations: ['the Riftstone Chamber', 'the Academy courtyard', 'a collapsing tower', 'the Nexus of Worlds'],
    loot: ['Dimensional Shard', 'Staff of Stability', 'Portal Key Fragment', 'Cloak of the Planes'],
    baseXP: 2,
  },
  {
    id: 'poison_identification',
    title: 'The Alchemist\'s Trial',
    sceneType: 'puzzle',
    intro: 'In {location}, {monster} has been poisoned! An array of reagents lines the shelf. Time is running out.',
    choices: [
      { label: 'Identify the antidote', stat: 'INT', baseThreshold: 3, successText: 'Your knowledge of alchemy saves the day! The antidote works. {monster} gifts you {loot} in gratitude.', failureText: 'You mix the wrong reagents — the solution fizzes uselessly. Someone else finds the cure.' },
      { label: 'Purge with vitality', stat: 'VIT', baseThreshold: 2, successText: 'You prepare a traditional herbal remedy from memory. Simple but effective! {monster} recovers and gives you {loot}.', failureText: 'Your herbal remedy tastes terrible and does nothing. Points for trying.' },
      { label: 'Inspire them to fight it', stat: 'WIL', baseThreshold: 2, successText: 'Your words of encouragement give {monster} the will to fight the poison! They pull through and hand you {loot}.', failureText: '"Your motivational speech is nice but I\'m literally dying," says {monster}. Fair point.' },
    ],
    monsters: ['the Village Elder', 'a wounded Knight', 'the Queen\'s advisor', 'a young dragon hatchling'],
    locations: ['the Healer\'s Hall', 'a battlefield apothecary', 'the Royal Chambers', 'an alchemist\'s workshop'],
    loot: ['Alchemist\'s Medallion', 'Vial of Clarity', 'Potion Recipe Book', 'Ring of Knowledge'],
    baseXP: 2,
  },

  // ═══════════ Social Encounters ═══════════
  {
    id: 'merchant_haggle',
    title: 'The Shrewd Merchant',
    sceneType: 'social',
    intro: 'In the bustling markets of {location}, {monster} guards a stall of rare treasures. The price is outrageous.',
    choices: [
      { label: 'Charm and haggle', stat: 'CRE', baseThreshold: 2, successText: 'Your wit wins the day! {monster} laughs and offers you {loot} at a fraction of the cost.', failureText: '{monster} sees right through your act. "Nice try. Full price or nothing."' },
      { label: 'Demonstrate your value', stat: 'STR', baseThreshold: 2, successText: 'You offer to guard the stall for an hour. {monster} is so grateful they give you {loot} as payment!', failureText: 'You flex intimidatingly. {monster} calls the guards. Wrong approach.' },
      { label: 'Analyze and find leverage', stat: 'INT', baseThreshold: 3, successText: 'You notice a flaw in {monster}\'s pricing. "This is a replica, not original." Embarrassed, they give you the real {loot}.', failureText: 'You try to outsmart {monster} but they\'ve been trading for 50 years. You\'re out of your depth.' },
    ],
    monsters: ['a Dwarven Trader', 'the Desert Fox Merchant', 'an Elvish Antiquarian', 'the Goblin Pawnbroker'],
    locations: ['the Grand Bazaar', 'Silverport Market', 'the Midnight Exchange', 'the Wanderer\'s Bazaar'],
    loot: ['Cloak of Charisma', 'Silver Tongue Pendant', 'Merchant\'s Lucky Coin', 'Bag of Holding'],
    baseXP: 2,
  },
  {
    id: 'disguise_infiltration',
    title: 'The Infiltration',
    sceneType: 'social',
    intro: 'The gates of {location} are sealed and guarded by {monster}. Inside lies something you need.',
    choices: [
      { label: 'Craft a disguise', stat: 'CRE', baseThreshold: 3, successText: 'Your disguise is flawless! {monster} waves you through. Inside, you secure {loot}.', failureText: 'Your fake mustache falls off in front of {monster}. Everyone has a good laugh. You\'re famous now.' },
      { label: 'Sneak past unseen', stat: 'VIT', baseThreshold: 2, successText: 'You move like a shadow, slipping past {monster} without a sound. {loot} is yours from inside.', failureText: 'You step on a twig. Then a cat. Then an alarm bell. Impressive streak of bad luck.' },
      { label: 'Intimidate your way in', stat: 'STR', baseThreshold: 3, successText: '"I\'m the new security chief," you growl. {monster} salutes and lets you in. {loot} acquired!', failureText: '{monster} laughs. "You? Security chief? You can\'t even open this jar."' },
    ],
    monsters: ['the Royal Guard', 'Orc Sentinels', 'Shadowkeep Wardens', 'the Night Watch'],
    locations: ['Castle Ironhold', 'the Forbidden Archives', 'the Shadow Guild Hall', 'the Dragon\'s Treasury'],
    loot: ['Mask of Many Faces', 'Ring of Invisibility', 'Cloak of Shadows', 'Boots of Silent Step'],
    baseXP: 2,
  },
  {
    id: 'bardic_duel',
    title: 'Bardic Duel',
    sceneType: 'social',
    intro: 'The crowd in {location} roars as {monster} takes the stage. They point at you. "Care to challenge me, adventurer?"',
    choices: [
      { label: 'Perform your heart out', stat: 'CRE', baseThreshold: 2, successText: 'Your performance brings the house down! Even {monster} applauds. The crowd showers you with {loot}!', failureText: '{monster}\'s performance is simply better today. The crowd politely claps for you.' },
      { label: 'Win the crowd with jokes', stat: 'WIL', baseThreshold: 3, successText: 'Your quick wit and self-deprecating humor steal the show! {monster} concedes. {loot} is your prize.', failureText: 'Your jokes land flat. Someone coughs. {monster} pats you on the back sympathetically.' },
      { label: 'Power ballad with energy', stat: 'VIT', baseThreshold: 2, successText: 'You belt out the most passionate, lung-busting performance ever heard! {monster} is moved to tears. {loot} earned!', failureText: 'You run out of breath mid-verse. {monster} finishes the song for you. Kind of them, honestly.' },
    ],
    monsters: ['the Silver Songstress', 'Bard King Melodius', 'the Phantom Violinist', 'Lady Lyric'],
    locations: ['the Golden Stage', 'the Festival of Stars', 'Moonhaven Amphitheater', 'the Eternal Concert Hall'],
    loot: ['Lyre of Inspiration', 'Crown of Creativity', 'Muse\'s Bracelet', 'Cape of Showmanship'],
    baseXP: 2,
  },
  {
    id: 'forgery_scroll',
    title: 'The Royal Checkpoint',
    sceneType: 'social',
    intro: 'The road through {location} is blocked by {monster} demanding official documents. You don\'t have them.',
    choices: [
      { label: 'Forge the documents', stat: 'CRE', baseThreshold: 3, successText: 'Your forged documents are a masterpiece. {monster} stamps them without hesitation. Past the checkpoint: {loot}.', failureText: 'You accidentally write "DEFINITELY NOT FORGED" on the document. {monster} frames it on the wall.' },
      { label: 'Negotiate passage', stat: 'WIL', baseThreshold: 2, successText: 'Your calm persistence wears down {monster}. They wave you through. On the other side: {loot}.', failureText: '"Rules are rules," says {monster} firmly. Your persuasion isn\'t enough today.' },
      { label: 'Find another route', stat: 'VIT', baseThreshold: 2, successText: 'You trek through rough terrain around the checkpoint. Exhausting but worth it — {loot} awaits beyond!', failureText: 'The detour is too harsh. You turn back, exhausted. The checkpoint wins this round.' },
    ],
    monsters: ['Imperial Inspectors', 'the Border Marshal', 'Customs Officers', 'the King\'s Auditors'],
    locations: ['the Northern Gate', 'Dragonpass Checkpoint', 'the City of Laws', 'the Merchant\'s Crossing'],
    loot: ['Master Forger\'s Kit', 'Seal of Authority', 'Quill of Perfection', 'Diplomat\'s Papers'],
    baseXP: 2,
  },

  // ═══════════ Endurance Encounters ═══════════
  {
    id: 'poison_cloud',
    title: 'The Spore Corridor',
    sceneType: 'endurance',
    intro: 'The only path through {location} is choked with toxic spores from {monster}. Each breath burns.',
    choices: [
      { label: 'Push through with grit', stat: 'VIT', baseThreshold: 2, successText: 'Holding your breath, you push through! Your body held strong. Waiting for you: {loot}.', failureText: 'The spores overwhelm you. You stumble back, coughing and dizzy.' },
      { label: 'Burn a path through', stat: 'STR', baseThreshold: 3, successText: 'You grab a torch and hack through the spore wall with brute force! The path clears. {loot} glimmers ahead.', failureText: 'The fire spreads the spores. More spores. So many more spores. You retreat.' },
      { label: 'Find a clean route', stat: 'INT', baseThreshold: 2, successText: 'You notice an air current — following it reveals a side tunnel with clean air. {loot} awaits at the end!', failureText: 'Your "clean route" leads deeper into the spore cloud. Bad navigation.' },
    ],
    monsters: ['Death Cap Colonies', 'Myconid Spore Lords', 'Toxic Fungi Clusters', 'the Blighted Growth'],
    locations: ['the Fungal Depths', 'the Underdark Passage', 'the Rotting Hollow', 'a poisoned mineshaft'],
    loot: ['Amulet of Poison Ward', 'Breath of Fresh Air Charm', 'Antitoxin Vial', 'Ring of Vitality'],
    baseXP: 2,
  },
  {
    id: 'frozen_pass',
    title: 'The Frozen Pass',
    sceneType: 'endurance',
    intro: 'A blizzard rages across {location}. {monster} turned back hours ago. The cold bites deep.',
    choices: [
      { label: 'Endure the cold', stat: 'VIT', baseThreshold: 3, successText: 'Step by frozen step, you conquer the pass! On the other side: shelter and {loot}.', failureText: 'The cold proves too much. You retreat to a cave. Survival is its own victory.' },
      { label: 'Build a shelter and wait', stat: 'INT', baseThreshold: 2, successText: 'You build an igloo from the snow itself. When the storm clears, you cross easily and find {loot}.', failureText: 'Your shelter collapses. Twice. You sit in the snow, questioning your life choices.' },
      { label: 'Sprint through the storm', stat: 'STR', baseThreshold: 2, successText: 'You charge through the blizzard like a berserker! Pure explosive energy gets you across. {loot} is your reward!', failureText: 'You sprint 50 meters and collapse. The blizzard is 5 miles wide. Math wasn\'t your strong suit.' },
    ],
    monsters: ['seasoned mountaineers', 'a Frost Giant patrol', 'the Yeti hunters', 'veteran Rangers'],
    locations: ['Howling Peak', 'the Shattered Ridge', 'Frostbite Pass', 'the Glacial Stairway'],
    loot: ['Cloak of Warmth', 'Frost-Walker Boots', 'Potion of Endurance', 'Heart of the Mountain'],
    baseXP: 2,
  },
  {
    id: 'desert_trek',
    title: 'The Scorching Wastes',
    sceneType: 'endurance',
    intro: 'The path to {location} crosses miles of blistering desert. {monster} marks the halfway point. The sun is merciless.',
    choices: [
      { label: 'March without stopping', stat: 'VIT', baseThreshold: 2, successText: 'Parched but unbroken, you reach {location}! Your endurance is rewarded with {loot}.', failureText: 'The heat forces you to rest. A passing caravan helps you back.' },
      { label: 'Navigate the cool route', stat: 'INT', baseThreshold: 3, successText: 'You chart a path through shaded canyons! Longer but cooler. At {location}, you find {loot}.', failureText: 'Your "shortcut" leads to a dead-end canyon. You waste hours backtracking.' },
      { label: 'Will yourself forward', stat: 'WIL', baseThreshold: 2, successText: 'Mind over matter. You refuse to stop. At {location}, {loot} waits like a mirage that\'s real.', failureText: 'Your willpower falters when you see a mirage oasis. You walk toward it for an hour. It\'s a cactus.' },
    ],
    monsters: ['a bleached obelisk', 'the Sandstone Sentinel', 'ancient desert ruins', 'a shimmering mirage'],
    locations: ['the Oasis of Solace', 'the Sun Temple', 'the Lost Caravan Route', 'the Golden Dunes'],
    loot: ['Sun Ward Amulet', 'Desert Rose Crystal', 'Canteen of Endless Water', 'Sandwalker\'s Charm'],
    baseXP: 2,
  },
  {
    id: 'cursed_feast',
    title: 'The Fey Lord\'s Banquet',
    sceneType: 'endurance',
    intro: 'In {location}, {monster} has set a magnificent feast. The food glows with enchantment. You must eat to honor the host — but resist the magic within.',
    choices: [
      { label: 'Iron constitution', stat: 'VIT', baseThreshold: 3, successText: 'You feast heartily and shrug off every enchantment! {monster} gifts you {loot}, impressed.', failureText: 'The enchanted wine gets the better of you. You wake up wearing a flower crown.' },
      { label: 'Resist the temptation', stat: 'WIL', baseThreshold: 2, successText: 'You eat just enough to be polite, resisting the magic. {monster} respects your discipline and offers {loot}.', failureText: '"Just one more bite..." Three hours later you\'re dancing on the table singing.' },
      { label: 'Outsmart the enchantment', stat: 'CRE', baseThreshold: 2, successText: 'You secretly swap the enchanted food with normal fare using sleight of hand! {monster} never notices. {loot} earned!', failureText: '{monster} catches you switching plates. "How RUDE!" The fey are deeply offended.' },
    ],
    monsters: ['the Archfey Oberon', 'Lady Titania', 'a Fey Trickster Lord', 'the Faerie Queen'],
    locations: ['the Feywild Court', 'Moonpetal Glade', 'the Enchanted Hollow', 'the Twilight Banquet Hall'],
    loot: ['Fey-Blessed Constitution', 'Goblet of Iron Will', 'Faerie Fruit Seed', 'Ring of Resistance'],
    baseXP: 2,
  },

  // ═══════════ Mental Encounters ═══════════
  {
    id: 'mind_flayer_gaze',
    title: 'Psychic Assault',
    sceneType: 'mental',
    intro: 'In the depths of {location}, {monster} turns its alien gaze upon you. Tendrils of thought bore into your mind.',
    choices: [
      { label: 'Build a mental fortress', stat: 'WIL', baseThreshold: 2, successText: 'Your mind is UNBREAKABLE! {monster} recoils. In its lair, you claim {loot}.', failureText: '{monster}\'s psychic tendrils are overwhelming. You retreat, shaken but intact.' },
      { label: 'Counter with logic', stat: 'INT', baseThreshold: 3, successText: 'You flood your mind with complex equations. {monster} gets a headache and retreats! {loot} is yours.', failureText: 'Your thoughts scatter. {monster} makes you forget your own name for five minutes.' },
      { label: 'Channel inner rage', stat: 'STR', baseThreshold: 2, successText: 'Pure fury burns away the psychic intrusion! You charge at {monster}, which flees. {loot} left behind!', failureText: 'Anger without focus makes you an easy target. {monster} redirects your rage into a wall. Ouch.' },
    ],
    monsters: ['a Mind Flayer', 'the Elder Brain', 'an Aboleth', 'a Psychic Wraith'],
    locations: ['the Mindstone Cavern', 'the Psionic Depths', 'the Tower of Thoughts', 'the Void Between'],
    loot: ['Helm of Mental Fortitude', 'Mindshield Pendant', 'Psionic Focus Crystal', 'Crown of Iron Will'],
    baseXP: 2,
  },
  {
    id: 'fear_corridor',
    title: 'The Hall of Nightmares',
    sceneType: 'mental',
    intro: '{location} stretches before you — a corridor of living nightmares conjured by {monster}. Your deepest fears manifest as shadows.',
    choices: [
      { label: 'Walk through unflinching', stat: 'WIL', baseThreshold: 3, successText: 'Eyes forward, heart steady. You walk through every nightmare without flinching. At the end: {loot}.', failureText: 'The nightmares are too vivid. You retreat. But facing them at all took courage.' },
      { label: 'Laugh at the illusions', stat: 'CRE', baseThreshold: 2, successText: 'You mock each nightmare with such humor they literally deflate! {monster}\'s magic crumbles. {loot} appears!', failureText: 'You try laughing but it comes out as a scream. Not the same energy.' },
      { label: 'Sprint through blind', stat: 'VIT', baseThreshold: 2, successText: 'Eyes shut, full sprint! You burst through the corridor in record time. {loot} waits on the other side!', failureText: 'Eyes shut + full sprint = you run into a wall. A very hard wall.' },
    ],
    monsters: ['the Dream Weaver', 'a Night Hag', 'the Fear Elemental', 'the Nightmare King'],
    locations: ['the Corridor of Shadows', 'the Dread Labyrinth', 'the Palace of Nightmares', 'the Haunted Gallery'],
    loot: ['Dreamcatcher Talisman', 'Lantern of Courage', 'Fearless Heart Gem', 'Shadow-Banishing Ring'],
    baseXP: 2,
  },
  {
    id: 'siren_song',
    title: 'The Siren\'s Call',
    sceneType: 'mental',
    intro: 'An enchanting melody drifts through {location}. {monster} sings from the abyss, pulling at your very soul.',
    choices: [
      { label: 'Steel your mind', stat: 'WIL', baseThreshold: 2, successText: 'You steel your mind against the song! Where it was strongest, you find {loot}.', failureText: 'The melody is intoxicating. You catch yourself walking toward the edge before snapping back.' },
      { label: 'Sing louder', stat: 'CRE', baseThreshold: 3, successText: 'You belt out YOUR OWN song so loudly it drowns out {monster}! They stop in shock. {loot} falls from the silence.', failureText: 'Your singing makes things worse. Now BOTH songs are awful. Everyone suffers.' },
      { label: 'Block your ears and charge', stat: 'STR', baseThreshold: 2, successText: 'Wax in ears, sword drawn — you charge past the siren! {monster} can\'t enchant what can\'t hear. {loot} claimed!', failureText: 'The wax falls out mid-charge. The song hits you. You start slow-dancing with a rock.' },
    ],
    monsters: ['the Abyssal Siren', 'an Enchantress', 'the Phantom Choir', 'a Harpy Songweaver'],
    locations: ['the Shattered Cliffs', 'the Whispering Shore', 'the Echoing Abyss', 'the Crystal Cavern'],
    loot: ['Earplugs of Clarity', 'Will-Forged Pendant', 'Amulet of Silence', 'Song-Breaker Stone'],
    baseXP: 2,
  },
  {
    id: 'shadow_self',
    title: 'The Shadow Mirror',
    sceneType: 'mental',
    intro: 'In {location}, a dark mirror reveals {monster} — a twisted version of yourself. It speaks with your voice: "Give in. Why keep fighting?"',
    choices: [
      { label: '"Because every step matters"', stat: 'WIL', baseThreshold: 3, successText: '"Because every small step matters," you reply. The shadow shatters! From the broken mirror falls {loot}.', failureText: 'The shadow\'s words cut deep. You turn away, shaken. But you didn\'t give in.' },
      { label: 'Outsmart your shadow', stat: 'INT', baseThreshold: 2, successText: '"You\'re just a reflection. You have no power I don\'t give you." The shadow dissolves. {loot} remains.', failureText: 'Your shadow is equally smart. It counters every argument. Stalemate.' },
      { label: 'Shatter the mirror', stat: 'STR', baseThreshold: 2, successText: 'You punch the mirror so hard it explodes! No reflection, no problem. {loot} flies from the shards!', failureText: 'You punch the mirror and it doesn\'t break. Your shadow slow-claps. Humiliating.' },
    ],
    monsters: ['your Shadow Self', 'the Dark Reflection', 'your Inner Doubt', 'the Phantom of Regret'],
    locations: ['the Mirror Sanctum', 'the Chamber of Truth', 'the Reflection Pool', 'the Temple of Self'],
    loot: ['Mirror of Resolve', 'Soul-Forged Amulet', 'Inner Fire Crystal', 'Mantle of Determination'],
    baseXP: 2,
  },
];

// ═══════════ Penalty Quests ═══════════

export const PENALTY_QUESTS = {
  STR: [
    { text: '30 squats', description: 'Drop and give your legs a burn! Strength is built through struggle.' },
    { text: '20 push-ups', description: 'Build that upper body. Your future self will thank you.' },
    { text: '1 min plank', description: 'Core strength is the foundation of everything.' },
  ],
  INT: [
    { text: 'Read for 10 min', description: 'Knowledge is the true weapon. Pick up any book.' },
    { text: 'Learn 5 new words', description: 'Expand your mind, one word at a time.' },
    { text: 'Watch an educational video', description: 'Feed your curiosity. Learn something new.' },
  ],
  CRE: [
    { text: '5 min sketch', description: 'Create something, anything. Perfection is the enemy.' },
    { text: 'Write 3 sentences', description: 'Express a thought. Let creativity flow.' },
    { text: 'Doodle freestyle for 3 min', description: 'No rules. Just draw.' },
  ],
  VIT: [
    { text: '10 min stretching', description: 'Flexibility is vitality. Your body will thank you.' },
    { text: 'Drink a full glass of water', description: 'Hydration heals all wounds.' },
    { text: '5 min deep breathing', description: 'Oxygenate your body. Slow, deep breaths.' },
  ],
  WIL: [
    { text: '5 min meditation', description: 'Still the mind. Sit with the silence.' },
    { text: '3 min cold exposure', description: 'Discipline through discomfort. Cold shower or ice.' },
    { text: 'Journal 5 sentences', description: 'Reflect on your day. Write honestly.' },
  ],
};

// ═══════════ Scene Sprites (16x16 grids) ═══════════

export const SCENE_PALETTES = {
  combat: { 1: '#8b0000', 2: '#cc3333', 3: '#ff6644', 4: '#ffaa44', 5: '#2a1a0a', 6: '#4a3020', 7: '#666' },
  puzzle: { 1: '#2a0845', 2: '#6c63ff', 3: '#a78bfa', 4: '#ddd6fe', 5: '#1a1a2e', 6: '#333366', 7: '#ffcc00' },
  social: { 1: '#5c3317', 2: '#8b6914', 3: '#d4a04a', 4: '#ffe4b5', 5: '#1a1a0a', 6: '#3a2a1a', 7: '#ff9944' },
  endurance: { 1: '#1a3a1a', 2: '#2d6b2d', 3: '#4ade80', 4: '#aaffaa', 5: '#0a1a0a', 6: '#1a2a1a', 7: '#ccff99' },
  mental: { 1: '#1a0a2e', 2: '#4a1a6e', 3: '#8b3ecf', 4: '#c77dff', 5: '#0a0a1a', 6: '#2a1a3e', 7: '#ff44ff' },
};

export const SCENE_SPRITES = {
  combat: [
    [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,1,2,2,1,0,0,0,0,0,0],
    [0,0,0,0,0,0,1,2,2,1,0,0,0,4,0,0],
    [0,0,0,0,0,0,0,1,1,0,0,0,4,0,0,0],
    [0,0,0,0,0,0,0,1,1,0,0,4,0,0,0,0],
    [0,0,0,0,0,1,1,1,1,1,1,4,0,0,0,0],
    [0,0,0,0,1,1,2,1,1,2,1,1,0,0,0,0],
    [0,0,0,0,1,1,2,1,1,2,1,1,0,0,0,0],
    [0,0,0,0,0,1,1,1,1,1,1,0,0,0,0,0],
    [0,0,0,0,0,1,1,1,1,1,1,0,0,0,0,0],
    [0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0],
    [0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0],
    [0,0,0,0,0,1,1,0,0,1,1,0,0,0,0,0],
    [5,5,5,5,5,6,6,5,5,6,6,5,5,5,5,5],
    [5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5],
  ],
  puzzle: [
    [0,0,0,0,5,5,5,5,5,5,5,5,0,0,0,0],
    [0,0,0,5,6,6,6,7,7,6,6,6,5,0,0,0],
    [0,0,5,6,1,1,1,1,1,1,1,1,6,5,0,0],
    [0,0,5,1,0,7,0,0,0,0,7,0,1,5,0,0],
    [0,0,5,1,0,0,0,0,0,0,0,0,1,5,0,0],
    [0,0,5,1,7,0,0,0,0,0,0,7,1,5,0,0],
    [0,0,5,1,0,0,0,2,2,0,0,0,1,5,0,0],
    [0,0,5,1,0,0,2,3,3,2,0,0,1,5,0,0],
    [0,0,5,1,0,0,2,3,3,2,0,0,1,5,0,0],
    [0,0,5,1,0,0,0,2,2,0,0,0,1,5,0,0],
    [0,0,5,1,7,0,0,0,0,0,0,7,1,5,0,0],
    [0,0,5,1,0,0,0,0,0,0,0,0,1,5,0,0],
    [0,0,5,1,0,7,0,0,0,0,7,0,1,5,0,0],
    [0,0,5,6,1,1,1,1,1,1,1,1,6,5,0,0],
    [5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5],
    [5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5],
  ],
  social: [
    [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,3,3,3,0,0,0,0,7,0,0],
    [0,0,0,0,0,3,4,4,4,3,0,0,0,7,0,0],
    [0,0,0,0,0,3,4,4,4,3,0,0,7,7,7,0],
    [0,0,0,0,0,0,3,3,3,0,0,0,0,7,0,0],
    [0,0,0,0,0,0,0,3,0,0,0,0,0,0,0,0],
    [0,0,0,0,3,3,3,3,3,3,3,0,0,0,0,0],
    [0,0,0,3,2,3,3,3,3,3,2,3,0,0,0,0],
    [0,0,0,0,3,3,3,3,3,3,3,0,0,0,0,0],
    [6,6,6,6,6,2,2,2,2,2,6,6,6,6,6,6],
    [1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1],
    [0,0,5,0,0,0,3,0,0,3,0,0,0,0,5,0],
    [0,0,5,0,0,0,3,0,0,3,0,0,0,0,5,0],
    [0,0,5,0,0,3,3,0,0,3,3,0,0,0,5,0],
    [5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5],
    [5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5],
  ],
  endurance: [
    [5,5,0,0,0,0,0,0,0,0,0,0,0,0,5,5],
    [5,0,0,0,3,0,0,0,0,0,0,3,0,0,0,5],
    [0,0,0,3,4,3,0,0,0,0,3,4,3,0,0,0],
    [0,0,0,0,3,0,0,0,0,0,0,3,0,0,0,0],
    [0,0,0,0,0,0,0,3,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,3,4,3,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,3,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
    [6,0,0,0,0,0,0,0,0,0,0,0,0,0,0,6],
    [2,6,0,0,0,0,0,0,0,0,0,0,0,0,6,2],
    [1,2,6,0,0,0,0,0,0,0,0,0,0,6,2,1],
    [1,1,2,6,6,6,6,6,6,6,6,6,6,2,1,1],
    [1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1],
  ],
  mental: [
    [5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5],
    [5,5,5,5,5,6,6,6,6,6,6,5,5,5,5,5],
    [5,5,5,6,6,1,1,1,1,1,1,6,6,5,5,5],
    [5,5,6,1,1,2,2,2,2,2,2,1,1,6,5,5],
    [5,6,1,2,2,3,3,3,3,3,3,2,2,1,6,5],
    [5,6,1,2,3,3,4,4,4,4,3,3,2,1,6,5],
    [5,6,1,2,3,4,7,7,7,7,4,3,2,1,6,5],
    [5,6,1,2,3,4,7,5,5,7,4,3,2,1,6,5],
    [5,6,1,2,3,4,7,5,5,7,4,3,2,1,6,5],
    [5,6,1,2,3,4,7,7,7,7,4,3,2,1,6,5],
    [5,6,1,2,3,3,4,4,4,4,3,3,2,1,6,5],
    [5,6,1,2,2,3,3,3,3,3,3,2,2,1,6,5],
    [5,5,6,1,1,2,2,2,2,2,2,1,1,6,5,5],
    [5,5,5,6,6,1,1,1,1,1,1,6,6,5,5,5],
    [5,5,5,5,5,6,6,6,6,6,6,5,5,5,5,5],
    [5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5],
  ],
};
